server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1234
  jpa:
    open-in--view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: crashreport@nsuslab.com
    password: Tupa0747
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
    default-expire-time: PT24H
    pool:
      max-active: 20
      max-idle: 20
      min-idle: 5
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
springdoc:
  packages-to-scan: org.example.projectnu
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: false
    display-request-duration: true
    operations-sorter: alpha
slack:
  webhook:
    url: https://hooks.slack.com/services/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
jwt:
  secret: your-256-bit-secret-key-here-should-be-32-characters-long-nsus-lab
  expiration: 3600000
