server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}
    encoding:
      charset: UTF-8
      enabled: ${SERVER_ENCODING_ENABLED}
      force: ${SERVER_ENCODING_FORCE}

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: ${JPA_OPEN_IN_VIEW}
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        show_sql: ${HIBERNATE_SHOW_SQL}
        format_sql: ${HIBERNATE_FORMAT_SQL}
        highlight_sql: ${HIBERNATE_HIGHLIGHT_SQL}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    default-expire-time: ${REDIS_DEFAULT_EXPIRE_TIME}
    pool:
      max-active: ${REDIS_POOL_MAX_ACTIVE}
      max-idle: ${REDIS_POOL_MAX_IDLE}
      min-idle: ${REDIS_POOL_MIN_IDLE}

logging:
  pattern:
    console: ${LOGGING_PATTERN_CONSOLE}
  level:
    org:
      hibernate:
        SQL: TRACE

springdoc:
  packages-to-scan: ${SPRINGDOC_PACKAGES_TO_SCAN}
  default-consumes-media-type: ${SPRINGDOC_DEFAULT_CONSUMES_MEDIA_TYPE}
  default-produces-media-type: ${SPRINGDOC_DEFAULT_PRODUCES_MEDIA_TYPE}
  swagger-ui:
    path: ${SWAGGER_UI_PATH}
    disable-swagger-default-url: ${SWAGGER_UI_DISABLE_DEFAULT_URL}
    display-request-duration: ${SWAGGER_UI_DISPLAY_REQUEST_DURATION}
    operations-sorter: ${SWAGGER_UI_OPERATIONS_SORTER}

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

jira:
  secret: ${JIRA_SECRET}
  email: ${JIRA_EMAIL}
oauth2:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    redirect-uri: ${OAUTH2_GOOGLE_REDIRECT_URI}
